# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
---
name: MegaLinter

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_STATUS_REPORTER: true
  GITHUB_COMMENT_REPORTER: false
  REPORTERS_MARKDOWN_TYPE: simple

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/terraform@v8.8.0
        id: ml

        env:
          VALIDATE_ALL_CODEBASE: "true"

      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log
